/*
Payment Processor Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paymentprocessor

import (
	"encoding/json"
	"fmt"
)

// checks if the PaymentprocessorGetPaymentMethodConfigurationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentprocessorGetPaymentMethodConfigurationRequest{}

// PaymentprocessorGetPaymentMethodConfigurationRequest struct for PaymentprocessorGetPaymentMethodConfigurationRequest
type PaymentprocessorGetPaymentMethodConfigurationRequest struct {
	TenantId string `json:"tenantId"`
	Code string `json:"code"`
	AdditionalProperties map[string]interface{}
}

type _PaymentprocessorGetPaymentMethodConfigurationRequest PaymentprocessorGetPaymentMethodConfigurationRequest

// NewPaymentprocessorGetPaymentMethodConfigurationRequest instantiates a new PaymentprocessorGetPaymentMethodConfigurationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentprocessorGetPaymentMethodConfigurationRequest(tenantId string, code string) *PaymentprocessorGetPaymentMethodConfigurationRequest {
	this := PaymentprocessorGetPaymentMethodConfigurationRequest{}
	this.TenantId = tenantId
	this.Code = code
	return &this
}

// NewPaymentprocessorGetPaymentMethodConfigurationRequestWithDefaults instantiates a new PaymentprocessorGetPaymentMethodConfigurationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentprocessorGetPaymentMethodConfigurationRequestWithDefaults() *PaymentprocessorGetPaymentMethodConfigurationRequest {
	this := PaymentprocessorGetPaymentMethodConfigurationRequest{}
	return &this
}

// GetTenantId returns the TenantId field value
func (o *PaymentprocessorGetPaymentMethodConfigurationRequest) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *PaymentprocessorGetPaymentMethodConfigurationRequest) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *PaymentprocessorGetPaymentMethodConfigurationRequest) SetTenantId(v string) {
	o.TenantId = v
}

// GetCode returns the Code field value
func (o *PaymentprocessorGetPaymentMethodConfigurationRequest) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *PaymentprocessorGetPaymentMethodConfigurationRequest) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *PaymentprocessorGetPaymentMethodConfigurationRequest) SetCode(v string) {
	o.Code = v
}

func (o PaymentprocessorGetPaymentMethodConfigurationRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentprocessorGetPaymentMethodConfigurationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tenantId"] = o.TenantId
	toSerialize["code"] = o.Code

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaymentprocessorGetPaymentMethodConfigurationRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tenantId",
		"code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaymentprocessorGetPaymentMethodConfigurationRequest := _PaymentprocessorGetPaymentMethodConfigurationRequest{}

	err = json.Unmarshal(data, &varPaymentprocessorGetPaymentMethodConfigurationRequest)

	if err != nil {
		return err
	}

	*o = PaymentprocessorGetPaymentMethodConfigurationRequest(varPaymentprocessorGetPaymentMethodConfigurationRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tenantId")
		delete(additionalProperties, "code")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *PaymentprocessorGetPaymentMethodConfigurationRequest) GetValue() interface{} {
	if o == nil || IsNil(o.Type) || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}
// SetValue populate the value of well-known types
func (o *PaymentprocessorGetPaymentMethodConfigurationRequest) SetValue(value interface{}) {
	if o == nil || IsNil(o.Type) || IsNil(value) {
		return
	}
    if IsNil(o.AdditionalProperties) {
        o.AdditionalProperties = map[string]interface{}{}
    }
	o.AdditionalProperties["value"] = value
	return
}
type NullablePaymentprocessorGetPaymentMethodConfigurationRequest struct {
	value *PaymentprocessorGetPaymentMethodConfigurationRequest
	isSet bool
}

func (v NullablePaymentprocessorGetPaymentMethodConfigurationRequest) Get() *PaymentprocessorGetPaymentMethodConfigurationRequest {
	return v.value
}

func (v *NullablePaymentprocessorGetPaymentMethodConfigurationRequest) Set(val *PaymentprocessorGetPaymentMethodConfigurationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentprocessorGetPaymentMethodConfigurationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentprocessorGetPaymentMethodConfigurationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentprocessorGetPaymentMethodConfigurationRequest(val *PaymentprocessorGetPaymentMethodConfigurationRequest) *NullablePaymentprocessorGetPaymentMethodConfigurationRequest {
	return &NullablePaymentprocessorGetPaymentMethodConfigurationRequest{value: val, isSet: true}
}

func (v NullablePaymentprocessorGetPaymentMethodConfigurationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentprocessorGetPaymentMethodConfigurationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


