/*
Payment Processor Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paymentprocessor

import (
	"encoding/json"
	"fmt"
)

// checks if the PaymentprocessorFinalizePaymentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentprocessorFinalizePaymentRequest{}

// PaymentprocessorFinalizePaymentRequest struct for PaymentprocessorFinalizePaymentRequest
type PaymentprocessorFinalizePaymentRequest struct {
	TenantId string `json:"tenantId"`
	PaymentId string `json:"paymentId"`
	Context *PaymentprocessorPaymentContext `json:"context,omitempty"`
	// payment type stripe, paypal..
	Code string `json:"code"`
	Amount *PaymentprocessorMoney `json:"amount,omitempty"`
	Currency *PaymentprocessorCurrency `json:"currency,omitempty"`
	AdditionalInfo *string `json:"additionalInfo,omitempty"`
	Transactions []PaymentprocessorTransaction `json:"transactions,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PaymentprocessorFinalizePaymentRequest PaymentprocessorFinalizePaymentRequest

// NewPaymentprocessorFinalizePaymentRequest instantiates a new PaymentprocessorFinalizePaymentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentprocessorFinalizePaymentRequest(tenantId string, paymentId string, code string) *PaymentprocessorFinalizePaymentRequest {
	this := PaymentprocessorFinalizePaymentRequest{}
	this.TenantId = tenantId
	this.PaymentId = paymentId
	this.Code = code
	var currency PaymentprocessorCurrency = PAYMENTPROCESSORCURRENCY_XXX
	this.Currency = &currency
	return &this
}

// NewPaymentprocessorFinalizePaymentRequestWithDefaults instantiates a new PaymentprocessorFinalizePaymentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentprocessorFinalizePaymentRequestWithDefaults() *PaymentprocessorFinalizePaymentRequest {
	this := PaymentprocessorFinalizePaymentRequest{}
	var currency PaymentprocessorCurrency = PAYMENTPROCESSORCURRENCY_XXX
	this.Currency = &currency
	return &this
}

// GetTenantId returns the TenantId field value
func (o *PaymentprocessorFinalizePaymentRequest) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *PaymentprocessorFinalizePaymentRequest) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *PaymentprocessorFinalizePaymentRequest) SetTenantId(v string) {
	o.TenantId = v
}

// GetPaymentId returns the PaymentId field value
func (o *PaymentprocessorFinalizePaymentRequest) GetPaymentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PaymentId
}

// GetPaymentIdOk returns a tuple with the PaymentId field value
// and a boolean to check if the value has been set.
func (o *PaymentprocessorFinalizePaymentRequest) GetPaymentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaymentId, true
}

// SetPaymentId sets field value
func (o *PaymentprocessorFinalizePaymentRequest) SetPaymentId(v string) {
	o.PaymentId = v
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *PaymentprocessorFinalizePaymentRequest) GetContext() PaymentprocessorPaymentContext {
	if o == nil || IsNil(o.Context) {
		var ret PaymentprocessorPaymentContext
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentprocessorFinalizePaymentRequest) GetContextOk() (*PaymentprocessorPaymentContext, bool) {
	if o == nil || IsNil(o.Context) {
		return nil, false
	}
	return o.Context, true
}

// &#39;Has&#39;Context returns a boolean if a field has been set.
func (o *PaymentprocessorFinalizePaymentRequest) &#39;Has&#39;Context() bool {
	if o != nil && !IsNil(o.Context) {
		return true
	}

	return false
}

// SetContext gets a reference to the given PaymentprocessorPaymentContext and assigns it to the Context field.
func (o *PaymentprocessorFinalizePaymentRequest) SetContext(v PaymentprocessorPaymentContext) {
	o.Context = &v
}

// GetCode returns the Code field value
func (o *PaymentprocessorFinalizePaymentRequest) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *PaymentprocessorFinalizePaymentRequest) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *PaymentprocessorFinalizePaymentRequest) SetCode(v string) {
	o.Code = v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *PaymentprocessorFinalizePaymentRequest) GetAmount() PaymentprocessorMoney {
	if o == nil || IsNil(o.Amount) {
		var ret PaymentprocessorMoney
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentprocessorFinalizePaymentRequest) GetAmountOk() (*PaymentprocessorMoney, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// &#39;Has&#39;Amount returns a boolean if a field has been set.
func (o *PaymentprocessorFinalizePaymentRequest) &#39;Has&#39;Amount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given PaymentprocessorMoney and assigns it to the Amount field.
func (o *PaymentprocessorFinalizePaymentRequest) SetAmount(v PaymentprocessorMoney) {
	o.Amount = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *PaymentprocessorFinalizePaymentRequest) GetCurrency() PaymentprocessorCurrency {
	if o == nil || IsNil(o.Currency) {
		var ret PaymentprocessorCurrency
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentprocessorFinalizePaymentRequest) GetCurrencyOk() (*PaymentprocessorCurrency, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// &#39;Has&#39;Currency returns a boolean if a field has been set.
func (o *PaymentprocessorFinalizePaymentRequest) &#39;Has&#39;Currency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given PaymentprocessorCurrency and assigns it to the Currency field.
func (o *PaymentprocessorFinalizePaymentRequest) SetCurrency(v PaymentprocessorCurrency) {
	o.Currency = &v
}

// GetAdditionalInfo returns the AdditionalInfo field value if set, zero value otherwise.
func (o *PaymentprocessorFinalizePaymentRequest) GetAdditionalInfo() string {
	if o == nil || IsNil(o.AdditionalInfo) {
		var ret string
		return ret
	}
	return *o.AdditionalInfo
}

// GetAdditionalInfoOk returns a tuple with the AdditionalInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentprocessorFinalizePaymentRequest) GetAdditionalInfoOk() (*string, bool) {
	if o == nil || IsNil(o.AdditionalInfo) {
		return nil, false
	}
	return o.AdditionalInfo, true
}

// &#39;Has&#39;AdditionalInfo returns a boolean if a field has been set.
func (o *PaymentprocessorFinalizePaymentRequest) &#39;Has&#39;AdditionalInfo() bool {
	if o != nil && !IsNil(o.AdditionalInfo) {
		return true
	}

	return false
}

// SetAdditionalInfo gets a reference to the given string and assigns it to the AdditionalInfo field.
func (o *PaymentprocessorFinalizePaymentRequest) SetAdditionalInfo(v string) {
	o.AdditionalInfo = &v
}

// GetTransactions returns the Transactions field value if set, zero value otherwise.
func (o *PaymentprocessorFinalizePaymentRequest) GetTransactions() []PaymentprocessorTransaction {
	if o == nil || IsNil(o.Transactions) {
		var ret []PaymentprocessorTransaction
		return ret
	}
	return o.Transactions
}

// GetTransactionsOk returns a tuple with the Transactions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentprocessorFinalizePaymentRequest) GetTransactionsOk() ([]PaymentprocessorTransaction, bool) {
	if o == nil || IsNil(o.Transactions) {
		return nil, false
	}
	return o.Transactions, true
}

// &#39;Has&#39;Transactions returns a boolean if a field has been set.
func (o *PaymentprocessorFinalizePaymentRequest) &#39;Has&#39;Transactions() bool {
	if o != nil && !IsNil(o.Transactions) {
		return true
	}

	return false
}

// SetTransactions gets a reference to the given []PaymentprocessorTransaction and assigns it to the Transactions field.
func (o *PaymentprocessorFinalizePaymentRequest) SetTransactions(v []PaymentprocessorTransaction) {
	o.Transactions = v
}

func (o PaymentprocessorFinalizePaymentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentprocessorFinalizePaymentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tenantId"] = o.TenantId
	toSerialize["paymentId"] = o.PaymentId
	if !IsNil(o.Context) {
		toSerialize["context"] = o.Context
	}
	toSerialize["code"] = o.Code
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.AdditionalInfo) {
		toSerialize["additionalInfo"] = o.AdditionalInfo
	}
	if !IsNil(o.Transactions) {
		toSerialize["transactions"] = o.Transactions
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaymentprocessorFinalizePaymentRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tenantId",
		"paymentId",
		"code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaymentprocessorFinalizePaymentRequest := _PaymentprocessorFinalizePaymentRequest{}

	err = json.Unmarshal(data, &varPaymentprocessorFinalizePaymentRequest)

	if err != nil {
		return err
	}

	*o = PaymentprocessorFinalizePaymentRequest(varPaymentprocessorFinalizePaymentRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tenantId")
		delete(additionalProperties, "paymentId")
		delete(additionalProperties, "context")
		delete(additionalProperties, "code")
		delete(additionalProperties, "amount")
		delete(additionalProperties, "currency")
		delete(additionalProperties, "additionalInfo")
		delete(additionalProperties, "transactions")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *PaymentprocessorFinalizePaymentRequest) GetValue() interface{} {
	if o == nil || IsNil(o.Type) || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}
// SetValue populate the value of well-known types
func (o *PaymentprocessorFinalizePaymentRequest) SetValue(value interface{}) {
	if o == nil || IsNil(o.Type) || IsNil(value) {
		return
	}
    if IsNil(o.AdditionalProperties) {
        o.AdditionalProperties = map[string]interface{}{}
    }
	o.AdditionalProperties["value"] = value
	return
}
type NullablePaymentprocessorFinalizePaymentRequest struct {
	value *PaymentprocessorFinalizePaymentRequest
	isSet bool
}

func (v NullablePaymentprocessorFinalizePaymentRequest) Get() *PaymentprocessorFinalizePaymentRequest {
	return v.value
}

func (v *NullablePaymentprocessorFinalizePaymentRequest) Set(val *PaymentprocessorFinalizePaymentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentprocessorFinalizePaymentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentprocessorFinalizePaymentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentprocessorFinalizePaymentRequest(val *PaymentprocessorFinalizePaymentRequest) *NullablePaymentprocessorFinalizePaymentRequest {
	return &NullablePaymentprocessorFinalizePaymentRequest{value: val, isSet: true}
}

func (v NullablePaymentprocessorFinalizePaymentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentprocessorFinalizePaymentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


