/*
Payment Processor Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paymentprocessor

import (
	"encoding/json"
	"fmt"
)

// checks if the PaymentprocessorListAvailablePaymentMethodsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentprocessorListAvailablePaymentMethodsRequest{}

// PaymentprocessorListAvailablePaymentMethodsRequest struct for PaymentprocessorListAvailablePaymentMethodsRequest
type PaymentprocessorListAvailablePaymentMethodsRequest struct {
	TenantId string `json:"tenantId"`
	Context PaymentprocessorAvailabilityContext `json:"context"`
	AuthenticateMethods *bool `json:"authenticateMethods,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PaymentprocessorListAvailablePaymentMethodsRequest PaymentprocessorListAvailablePaymentMethodsRequest

// NewPaymentprocessorListAvailablePaymentMethodsRequest instantiates a new PaymentprocessorListAvailablePaymentMethodsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentprocessorListAvailablePaymentMethodsRequest(tenantId string, context PaymentprocessorAvailabilityContext) *PaymentprocessorListAvailablePaymentMethodsRequest {
	this := PaymentprocessorListAvailablePaymentMethodsRequest{}
	this.TenantId = tenantId
	this.Context = context
	return &this
}

// NewPaymentprocessorListAvailablePaymentMethodsRequestWithDefaults instantiates a new PaymentprocessorListAvailablePaymentMethodsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentprocessorListAvailablePaymentMethodsRequestWithDefaults() *PaymentprocessorListAvailablePaymentMethodsRequest {
	this := PaymentprocessorListAvailablePaymentMethodsRequest{}
	return &this
}

// GetTenantId returns the TenantId field value
func (o *PaymentprocessorListAvailablePaymentMethodsRequest) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *PaymentprocessorListAvailablePaymentMethodsRequest) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *PaymentprocessorListAvailablePaymentMethodsRequest) SetTenantId(v string) {
	o.TenantId = v
}

// GetContext returns the Context field value
func (o *PaymentprocessorListAvailablePaymentMethodsRequest) GetContext() PaymentprocessorAvailabilityContext {
	if o == nil {
		var ret PaymentprocessorAvailabilityContext
		return ret
	}

	return o.Context
}

// GetContextOk returns a tuple with the Context field value
// and a boolean to check if the value has been set.
func (o *PaymentprocessorListAvailablePaymentMethodsRequest) GetContextOk() (*PaymentprocessorAvailabilityContext, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Context, true
}

// SetContext sets field value
func (o *PaymentprocessorListAvailablePaymentMethodsRequest) SetContext(v PaymentprocessorAvailabilityContext) {
	o.Context = v
}

// GetAuthenticateMethods returns the AuthenticateMethods field value if set, zero value otherwise.
func (o *PaymentprocessorListAvailablePaymentMethodsRequest) GetAuthenticateMethods() bool {
	if o == nil || IsNil(o.AuthenticateMethods) {
		var ret bool
		return ret
	}
	return *o.AuthenticateMethods
}

// GetAuthenticateMethodsOk returns a tuple with the AuthenticateMethods field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentprocessorListAvailablePaymentMethodsRequest) GetAuthenticateMethodsOk() (*bool, bool) {
	if o == nil || IsNil(o.AuthenticateMethods) {
		return nil, false
	}
	return o.AuthenticateMethods, true
}

// &#39;Has&#39;AuthenticateMethods returns a boolean if a field has been set.
func (o *PaymentprocessorListAvailablePaymentMethodsRequest) &#39;Has&#39;AuthenticateMethods() bool {
	if o != nil && !IsNil(o.AuthenticateMethods) {
		return true
	}

	return false
}

// SetAuthenticateMethods gets a reference to the given bool and assigns it to the AuthenticateMethods field.
func (o *PaymentprocessorListAvailablePaymentMethodsRequest) SetAuthenticateMethods(v bool) {
	o.AuthenticateMethods = &v
}

func (o PaymentprocessorListAvailablePaymentMethodsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentprocessorListAvailablePaymentMethodsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tenantId"] = o.TenantId
	toSerialize["context"] = o.Context
	if !IsNil(o.AuthenticateMethods) {
		toSerialize["authenticateMethods"] = o.AuthenticateMethods
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaymentprocessorListAvailablePaymentMethodsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tenantId",
		"context",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaymentprocessorListAvailablePaymentMethodsRequest := _PaymentprocessorListAvailablePaymentMethodsRequest{}

	err = json.Unmarshal(data, &varPaymentprocessorListAvailablePaymentMethodsRequest)

	if err != nil {
		return err
	}

	*o = PaymentprocessorListAvailablePaymentMethodsRequest(varPaymentprocessorListAvailablePaymentMethodsRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tenantId")
		delete(additionalProperties, "context")
		delete(additionalProperties, "authenticateMethods")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *PaymentprocessorListAvailablePaymentMethodsRequest) GetValue() interface{} {
	if o == nil || IsNil(o.Type) || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}
// SetValue populate the value of well-known types
func (o *PaymentprocessorListAvailablePaymentMethodsRequest) SetValue(value interface{}) {
	if o == nil || IsNil(o.Type) || IsNil(value) {
		return
	}
    if IsNil(o.AdditionalProperties) {
        o.AdditionalProperties = map[string]interface{}{}
    }
	o.AdditionalProperties["value"] = value
	return
}
type NullablePaymentprocessorListAvailablePaymentMethodsRequest struct {
	value *PaymentprocessorListAvailablePaymentMethodsRequest
	isSet bool
}

func (v NullablePaymentprocessorListAvailablePaymentMethodsRequest) Get() *PaymentprocessorListAvailablePaymentMethodsRequest {
	return v.value
}

func (v *NullablePaymentprocessorListAvailablePaymentMethodsRequest) Set(val *PaymentprocessorListAvailablePaymentMethodsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentprocessorListAvailablePaymentMethodsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentprocessorListAvailablePaymentMethodsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentprocessorListAvailablePaymentMethodsRequest(val *PaymentprocessorListAvailablePaymentMethodsRequest) *NullablePaymentprocessorListAvailablePaymentMethodsRequest {
	return &NullablePaymentprocessorListAvailablePaymentMethodsRequest{value: val, isSet: true}
}

func (v NullablePaymentprocessorListAvailablePaymentMethodsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentprocessorListAvailablePaymentMethodsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


