/*
Payment Processor Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paymentprocessor

import (
	"encoding/json"
	"fmt"
)

// checks if the PaymentprocessorCreatePaymentMethodRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentprocessorCreatePaymentMethodRequest{}

// PaymentprocessorCreatePaymentMethodRequest struct for PaymentprocessorCreatePaymentMethodRequest
type PaymentprocessorCreatePaymentMethodRequest struct {
	TenantId string `json:"tenantId"`
	Code string `json:"code"`
	Title PaymentprocessorLocalizedText `json:"title"`
	Label *PaymentprocessorLocalizedText `json:"label,omitempty"`
	Enabled *bool `json:"enabled,omitempty"`
	Amount *PaymentprocessorMoney `json:"amount,omitempty"`
	Currency *PaymentprocessorCurrency `json:"currency,omitempty"`
	Configuration map[string]interface{} `json:"configuration,omitempty"`
	IsUpfront *bool `json:"isUpfront,omitempty"`
	Description *PaymentprocessorLocalizedText `json:"description,omitempty"`
	Restrictions []PaymentprocessorPaymentMethodRestriction `json:"restrictions,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PaymentprocessorCreatePaymentMethodRequest PaymentprocessorCreatePaymentMethodRequest

// NewPaymentprocessorCreatePaymentMethodRequest instantiates a new PaymentprocessorCreatePaymentMethodRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentprocessorCreatePaymentMethodRequest(tenantId string, code string, title PaymentprocessorLocalizedText) *PaymentprocessorCreatePaymentMethodRequest {
	this := PaymentprocessorCreatePaymentMethodRequest{}
	this.TenantId = tenantId
	this.Code = code
	this.Title = title
	var currency PaymentprocessorCurrency = PAYMENTPROCESSORCURRENCY_XXX
	this.Currency = &currency
	return &this
}

// NewPaymentprocessorCreatePaymentMethodRequestWithDefaults instantiates a new PaymentprocessorCreatePaymentMethodRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentprocessorCreatePaymentMethodRequestWithDefaults() *PaymentprocessorCreatePaymentMethodRequest {
	this := PaymentprocessorCreatePaymentMethodRequest{}
	var currency PaymentprocessorCurrency = PAYMENTPROCESSORCURRENCY_XXX
	this.Currency = &currency
	return &this
}

// GetTenantId returns the TenantId field value
func (o *PaymentprocessorCreatePaymentMethodRequest) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *PaymentprocessorCreatePaymentMethodRequest) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *PaymentprocessorCreatePaymentMethodRequest) SetTenantId(v string) {
	o.TenantId = v
}

// GetCode returns the Code field value
func (o *PaymentprocessorCreatePaymentMethodRequest) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *PaymentprocessorCreatePaymentMethodRequest) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *PaymentprocessorCreatePaymentMethodRequest) SetCode(v string) {
	o.Code = v
}

// GetTitle returns the Title field value
func (o *PaymentprocessorCreatePaymentMethodRequest) GetTitle() PaymentprocessorLocalizedText {
	if o == nil {
		var ret PaymentprocessorLocalizedText
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *PaymentprocessorCreatePaymentMethodRequest) GetTitleOk() (*PaymentprocessorLocalizedText, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *PaymentprocessorCreatePaymentMethodRequest) SetTitle(v PaymentprocessorLocalizedText) {
	o.Title = v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *PaymentprocessorCreatePaymentMethodRequest) GetLabel() PaymentprocessorLocalizedText {
	if o == nil || IsNil(o.Label) {
		var ret PaymentprocessorLocalizedText
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentprocessorCreatePaymentMethodRequest) GetLabelOk() (*PaymentprocessorLocalizedText, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// &#39;Has&#39;Label returns a boolean if a field has been set.
func (o *PaymentprocessorCreatePaymentMethodRequest) &#39;Has&#39;Label() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given PaymentprocessorLocalizedText and assigns it to the Label field.
func (o *PaymentprocessorCreatePaymentMethodRequest) SetLabel(v PaymentprocessorLocalizedText) {
	o.Label = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *PaymentprocessorCreatePaymentMethodRequest) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentprocessorCreatePaymentMethodRequest) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// &#39;Has&#39;Enabled returns a boolean if a field has been set.
func (o *PaymentprocessorCreatePaymentMethodRequest) &#39;Has&#39;Enabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *PaymentprocessorCreatePaymentMethodRequest) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *PaymentprocessorCreatePaymentMethodRequest) GetAmount() PaymentprocessorMoney {
	if o == nil || IsNil(o.Amount) {
		var ret PaymentprocessorMoney
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentprocessorCreatePaymentMethodRequest) GetAmountOk() (*PaymentprocessorMoney, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// &#39;Has&#39;Amount returns a boolean if a field has been set.
func (o *PaymentprocessorCreatePaymentMethodRequest) &#39;Has&#39;Amount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given PaymentprocessorMoney and assigns it to the Amount field.
func (o *PaymentprocessorCreatePaymentMethodRequest) SetAmount(v PaymentprocessorMoney) {
	o.Amount = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *PaymentprocessorCreatePaymentMethodRequest) GetCurrency() PaymentprocessorCurrency {
	if o == nil || IsNil(o.Currency) {
		var ret PaymentprocessorCurrency
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentprocessorCreatePaymentMethodRequest) GetCurrencyOk() (*PaymentprocessorCurrency, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// &#39;Has&#39;Currency returns a boolean if a field has been set.
func (o *PaymentprocessorCreatePaymentMethodRequest) &#39;Has&#39;Currency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given PaymentprocessorCurrency and assigns it to the Currency field.
func (o *PaymentprocessorCreatePaymentMethodRequest) SetCurrency(v PaymentprocessorCurrency) {
	o.Currency = &v
}

// GetConfiguration returns the Configuration field value if set, zero value otherwise.
func (o *PaymentprocessorCreatePaymentMethodRequest) GetConfiguration() map[string]interface{} {
	if o == nil || IsNil(o.Configuration) {
		var ret map[string]interface{}
		return ret
	}
	return o.Configuration
}

// GetConfigurationOk returns a tuple with the Configuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentprocessorCreatePaymentMethodRequest) GetConfigurationOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Configuration) {
		return map[string]interface{}{}, false
	}
	return o.Configuration, true
}

// &#39;Has&#39;Configuration returns a boolean if a field has been set.
func (o *PaymentprocessorCreatePaymentMethodRequest) &#39;Has&#39;Configuration() bool {
	if o != nil && !IsNil(o.Configuration) {
		return true
	}

	return false
}

// SetConfiguration gets a reference to the given map[string]interface{} and assigns it to the Configuration field.
func (o *PaymentprocessorCreatePaymentMethodRequest) SetConfiguration(v map[string]interface{}) {
	o.Configuration = v
}

// GetIsUpfront returns the IsUpfront field value if set, zero value otherwise.
func (o *PaymentprocessorCreatePaymentMethodRequest) GetIsUpfront() bool {
	if o == nil || IsNil(o.IsUpfront) {
		var ret bool
		return ret
	}
	return *o.IsUpfront
}

// GetIsUpfrontOk returns a tuple with the IsUpfront field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentprocessorCreatePaymentMethodRequest) GetIsUpfrontOk() (*bool, bool) {
	if o == nil || IsNil(o.IsUpfront) {
		return nil, false
	}
	return o.IsUpfront, true
}

// &#39;Has&#39;IsUpfront returns a boolean if a field has been set.
func (o *PaymentprocessorCreatePaymentMethodRequest) &#39;Has&#39;IsUpfront() bool {
	if o != nil && !IsNil(o.IsUpfront) {
		return true
	}

	return false
}

// SetIsUpfront gets a reference to the given bool and assigns it to the IsUpfront field.
func (o *PaymentprocessorCreatePaymentMethodRequest) SetIsUpfront(v bool) {
	o.IsUpfront = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *PaymentprocessorCreatePaymentMethodRequest) GetDescription() PaymentprocessorLocalizedText {
	if o == nil || IsNil(o.Description) {
		var ret PaymentprocessorLocalizedText
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentprocessorCreatePaymentMethodRequest) GetDescriptionOk() (*PaymentprocessorLocalizedText, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// &#39;Has&#39;Description returns a boolean if a field has been set.
func (o *PaymentprocessorCreatePaymentMethodRequest) &#39;Has&#39;Description() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given PaymentprocessorLocalizedText and assigns it to the Description field.
func (o *PaymentprocessorCreatePaymentMethodRequest) SetDescription(v PaymentprocessorLocalizedText) {
	o.Description = &v
}

// GetRestrictions returns the Restrictions field value if set, zero value otherwise.
func (o *PaymentprocessorCreatePaymentMethodRequest) GetRestrictions() []PaymentprocessorPaymentMethodRestriction {
	if o == nil || IsNil(o.Restrictions) {
		var ret []PaymentprocessorPaymentMethodRestriction
		return ret
	}
	return o.Restrictions
}

// GetRestrictionsOk returns a tuple with the Restrictions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentprocessorCreatePaymentMethodRequest) GetRestrictionsOk() ([]PaymentprocessorPaymentMethodRestriction, bool) {
	if o == nil || IsNil(o.Restrictions) {
		return nil, false
	}
	return o.Restrictions, true
}

// &#39;Has&#39;Restrictions returns a boolean if a field has been set.
func (o *PaymentprocessorCreatePaymentMethodRequest) &#39;Has&#39;Restrictions() bool {
	if o != nil && !IsNil(o.Restrictions) {
		return true
	}

	return false
}

// SetRestrictions gets a reference to the given []PaymentprocessorPaymentMethodRestriction and assigns it to the Restrictions field.
func (o *PaymentprocessorCreatePaymentMethodRequest) SetRestrictions(v []PaymentprocessorPaymentMethodRestriction) {
	o.Restrictions = v
}

func (o PaymentprocessorCreatePaymentMethodRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentprocessorCreatePaymentMethodRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tenantId"] = o.TenantId
	toSerialize["code"] = o.Code
	toSerialize["title"] = o.Title
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.Configuration) {
		toSerialize["configuration"] = o.Configuration
	}
	if !IsNil(o.IsUpfront) {
		toSerialize["isUpfront"] = o.IsUpfront
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Restrictions) {
		toSerialize["restrictions"] = o.Restrictions
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaymentprocessorCreatePaymentMethodRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tenantId",
		"code",
		"title",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaymentprocessorCreatePaymentMethodRequest := _PaymentprocessorCreatePaymentMethodRequest{}

	err = json.Unmarshal(data, &varPaymentprocessorCreatePaymentMethodRequest)

	if err != nil {
		return err
	}

	*o = PaymentprocessorCreatePaymentMethodRequest(varPaymentprocessorCreatePaymentMethodRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tenantId")
		delete(additionalProperties, "code")
		delete(additionalProperties, "title")
		delete(additionalProperties, "label")
		delete(additionalProperties, "enabled")
		delete(additionalProperties, "amount")
		delete(additionalProperties, "currency")
		delete(additionalProperties, "configuration")
		delete(additionalProperties, "isUpfront")
		delete(additionalProperties, "description")
		delete(additionalProperties, "restrictions")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *PaymentprocessorCreatePaymentMethodRequest) GetValue() interface{} {
	if o == nil || IsNil(o.Type) || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}
// SetValue populate the value of well-known types
func (o *PaymentprocessorCreatePaymentMethodRequest) SetValue(value interface{}) {
	if o == nil || IsNil(o.Type) || IsNil(value) {
		return
	}
    if IsNil(o.AdditionalProperties) {
        o.AdditionalProperties = map[string]interface{}{}
    }
	o.AdditionalProperties["value"] = value
	return
}
type NullablePaymentprocessorCreatePaymentMethodRequest struct {
	value *PaymentprocessorCreatePaymentMethodRequest
	isSet bool
}

func (v NullablePaymentprocessorCreatePaymentMethodRequest) Get() *PaymentprocessorCreatePaymentMethodRequest {
	return v.value
}

func (v *NullablePaymentprocessorCreatePaymentMethodRequest) Set(val *PaymentprocessorCreatePaymentMethodRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentprocessorCreatePaymentMethodRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentprocessorCreatePaymentMethodRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentprocessorCreatePaymentMethodRequest(val *PaymentprocessorCreatePaymentMethodRequest) *NullablePaymentprocessorCreatePaymentMethodRequest {
	return &NullablePaymentprocessorCreatePaymentMethodRequest{value: val, isSet: true}
}

func (v NullablePaymentprocessorCreatePaymentMethodRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentprocessorCreatePaymentMethodRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


