/*
Payment Processor Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paymentprocessor

import (
	"encoding/json"
)

// checks if the PaymentprocessorFinalizePaymentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentprocessorFinalizePaymentResponse{}

// PaymentprocessorFinalizePaymentResponse struct for PaymentprocessorFinalizePaymentResponse
type PaymentprocessorFinalizePaymentResponse struct {
	Transaction *PaymentprocessorTransaction `json:"transaction,omitempty"`
	ErrorMessage *string `json:"errorMessage,omitempty"`
}

// NewPaymentprocessorFinalizePaymentResponse instantiates a new PaymentprocessorFinalizePaymentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentprocessorFinalizePaymentResponse() *PaymentprocessorFinalizePaymentResponse {
	this := PaymentprocessorFinalizePaymentResponse{}
	return &this
}

// NewPaymentprocessorFinalizePaymentResponseWithDefaults instantiates a new PaymentprocessorFinalizePaymentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentprocessorFinalizePaymentResponseWithDefaults() *PaymentprocessorFinalizePaymentResponse {
	this := PaymentprocessorFinalizePaymentResponse{}
	return &this
}

// GetTransaction returns the Transaction field value if set, zero value otherwise.
func (o *PaymentprocessorFinalizePaymentResponse) GetTransaction() PaymentprocessorTransaction {
	if o == nil || IsNil(o.Transaction) {
		var ret PaymentprocessorTransaction
		return ret
	}
	return *o.Transaction
}

// GetTransactionOk returns a tuple with the Transaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentprocessorFinalizePaymentResponse) GetTransactionOk() (*PaymentprocessorTransaction, bool) {
	if o == nil || IsNil(o.Transaction) {
		return nil, false
	}
	return o.Transaction, true
}

// HasTransaction returns a boolean if a field has been set.
func (o *PaymentprocessorFinalizePaymentResponse) HasTransaction() bool {
	if o != nil && !IsNil(o.Transaction) {
		return true
	}

	return false
}

// SetTransaction gets a reference to the given PaymentprocessorTransaction and assigns it to the Transaction field.
func (o *PaymentprocessorFinalizePaymentResponse) SetTransaction(v PaymentprocessorTransaction) {
	o.Transaction = &v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise.
func (o *PaymentprocessorFinalizePaymentResponse) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage) {
		var ret string
		return ret
	}
	return *o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentprocessorFinalizePaymentResponse) GetErrorMessageOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorMessage) {
		return nil, false
	}
	return o.ErrorMessage, true
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *PaymentprocessorFinalizePaymentResponse) HasErrorMessage() bool {
	if o != nil && !IsNil(o.ErrorMessage) {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given string and assigns it to the ErrorMessage field.
func (o *PaymentprocessorFinalizePaymentResponse) SetErrorMessage(v string) {
	o.ErrorMessage = &v
}

func (o PaymentprocessorFinalizePaymentResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentprocessorFinalizePaymentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Transaction) {
		toSerialize["transaction"] = o.Transaction
	}
	if !IsNil(o.ErrorMessage) {
		toSerialize["errorMessage"] = o.ErrorMessage
	}
	return toSerialize, nil
}

type NullablePaymentprocessorFinalizePaymentResponse struct {
	value *PaymentprocessorFinalizePaymentResponse
	isSet bool
}

func (v NullablePaymentprocessorFinalizePaymentResponse) Get() *PaymentprocessorFinalizePaymentResponse {
	return v.value
}

func (v *NullablePaymentprocessorFinalizePaymentResponse) Set(val *PaymentprocessorFinalizePaymentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentprocessorFinalizePaymentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentprocessorFinalizePaymentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentprocessorFinalizePaymentResponse(val *PaymentprocessorFinalizePaymentResponse) *NullablePaymentprocessorFinalizePaymentResponse {
	return &NullablePaymentprocessorFinalizePaymentResponse{value: val, isSet: true}
}

func (v NullablePaymentprocessorFinalizePaymentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentprocessorFinalizePaymentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


