/*
Payment Processor Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paymentprocessor

import (
	"encoding/json"
	"fmt"
)

// checks if the PaymentprocessorTransaction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentprocessorTransaction{}

// PaymentprocessorTransaction struct for PaymentprocessorTransaction
type PaymentprocessorTransaction struct {
	PaymentId string `json:"paymentId"`
	Id string `json:"id"`
	Type *PaymentprocessorTransactionType `json:"type,omitempty"`
	AdditionalInfo *string `json:"additionalInfo,omitempty"`
	ChildTransactions []PaymentprocessorTransaction `json:"childTransactions,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PaymentprocessorTransaction PaymentprocessorTransaction

// NewPaymentprocessorTransaction instantiates a new PaymentprocessorTransaction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentprocessorTransaction(paymentId string, id string) *PaymentprocessorTransaction {
	this := PaymentprocessorTransaction{}
	this.PaymentId = paymentId
	this.Id = id
	var type_ PaymentprocessorTransactionType = PAYMENTPROCESSORTRANSACTIONTYPE_UNKNOWN
	this.Type = &type_
	return &this
}

// NewPaymentprocessorTransactionWithDefaults instantiates a new PaymentprocessorTransaction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentprocessorTransactionWithDefaults() *PaymentprocessorTransaction {
	this := PaymentprocessorTransaction{}
	var type_ PaymentprocessorTransactionType = PAYMENTPROCESSORTRANSACTIONTYPE_UNKNOWN
	this.Type = &type_
	return &this
}

// GetPaymentId returns the PaymentId field value
func (o *PaymentprocessorTransaction) GetPaymentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PaymentId
}

// GetPaymentIdOk returns a tuple with the PaymentId field value
// and a boolean to check if the value has been set.
func (o *PaymentprocessorTransaction) GetPaymentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaymentId, true
}

// SetPaymentId sets field value
func (o *PaymentprocessorTransaction) SetPaymentId(v string) {
	o.PaymentId = v
}

// GetId returns the Id field value
func (o *PaymentprocessorTransaction) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PaymentprocessorTransaction) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PaymentprocessorTransaction) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *PaymentprocessorTransaction) GetType() PaymentprocessorTransactionType {
	if o == nil || IsNil(o.Type) {
		var ret PaymentprocessorTransactionType
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentprocessorTransaction) GetTypeOk() (*PaymentprocessorTransactionType, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *PaymentprocessorTransaction) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given PaymentprocessorTransactionType and assigns it to the Type field.
func (o *PaymentprocessorTransaction) SetType(v PaymentprocessorTransactionType) {
	o.Type = &v
}

// GetAdditionalInfo returns the AdditionalInfo field value if set, zero value otherwise.
func (o *PaymentprocessorTransaction) GetAdditionalInfo() string {
	if o == nil || IsNil(o.AdditionalInfo) {
		var ret string
		return ret
	}
	return *o.AdditionalInfo
}

// GetAdditionalInfoOk returns a tuple with the AdditionalInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentprocessorTransaction) GetAdditionalInfoOk() (*string, bool) {
	if o == nil || IsNil(o.AdditionalInfo) {
		return nil, false
	}
	return o.AdditionalInfo, true
}

// HasAdditionalInfo returns a boolean if a field has been set.
func (o *PaymentprocessorTransaction) HasAdditionalInfo() bool {
	if o != nil && !IsNil(o.AdditionalInfo) {
		return true
	}

	return false
}

// SetAdditionalInfo gets a reference to the given string and assigns it to the AdditionalInfo field.
func (o *PaymentprocessorTransaction) SetAdditionalInfo(v string) {
	o.AdditionalInfo = &v
}

// GetChildTransactions returns the ChildTransactions field value if set, zero value otherwise.
func (o *PaymentprocessorTransaction) GetChildTransactions() []PaymentprocessorTransaction {
	if o == nil || IsNil(o.ChildTransactions) {
		var ret []PaymentprocessorTransaction
		return ret
	}
	return o.ChildTransactions
}

// GetChildTransactionsOk returns a tuple with the ChildTransactions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentprocessorTransaction) GetChildTransactionsOk() ([]PaymentprocessorTransaction, bool) {
	if o == nil || IsNil(o.ChildTransactions) {
		return nil, false
	}
	return o.ChildTransactions, true
}

// HasChildTransactions returns a boolean if a field has been set.
func (o *PaymentprocessorTransaction) HasChildTransactions() bool {
	if o != nil && !IsNil(o.ChildTransactions) {
		return true
	}

	return false
}

// SetChildTransactions gets a reference to the given []PaymentprocessorTransaction and assigns it to the ChildTransactions field.
func (o *PaymentprocessorTransaction) SetChildTransactions(v []PaymentprocessorTransaction) {
	o.ChildTransactions = v
}

func (o PaymentprocessorTransaction) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentprocessorTransaction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["paymentId"] = o.PaymentId
	toSerialize["id"] = o.Id
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.AdditionalInfo) {
		toSerialize["additionalInfo"] = o.AdditionalInfo
	}
	if !IsNil(o.ChildTransactions) {
		toSerialize["childTransactions"] = o.ChildTransactions
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaymentprocessorTransaction) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"paymentId",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaymentprocessorTransaction := _PaymentprocessorTransaction{}

	err = json.Unmarshal(data, &varPaymentprocessorTransaction)

	if err != nil {
		return err
	}

	*o = PaymentprocessorTransaction(varPaymentprocessorTransaction)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "paymentId")
		delete(additionalProperties, "id")
		delete(additionalProperties, "type")
		delete(additionalProperties, "additionalInfo")
		delete(additionalProperties, "childTransactions")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *PaymentprocessorTransaction) GetValue() interface{} {
	if o == nil || IsNil(o.Type) || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}
// SetValue populate the value of well-known types
func (o *PaymentprocessorTransaction) SetValue(value interface{}) {
	if o == nil || IsNil(o.Type) || IsNil(value) {
		return
	}
    if IsNil(o.AdditionalProperties) {
        o.AdditionalProperties = map[string]interface{}{}
    }
	o.AdditionalProperties["value"] = value
	return
}
type NullablePaymentprocessorTransaction struct {
	value *PaymentprocessorTransaction
	isSet bool
}

func (v NullablePaymentprocessorTransaction) Get() *PaymentprocessorTransaction {
	return v.value
}

func (v *NullablePaymentprocessorTransaction) Set(val *PaymentprocessorTransaction) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentprocessorTransaction) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentprocessorTransaction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentprocessorTransaction(val *PaymentprocessorTransaction) *NullablePaymentprocessorTransaction {
	return &NullablePaymentprocessorTransaction{value: val, isSet: true}
}

func (v NullablePaymentprocessorTransaction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentprocessorTransaction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


