/*
Payment Processor Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paymentprocessor

import (
	"encoding/json"
)

// checks if the PaymentprocessorVoidPaymentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentprocessorVoidPaymentResponse{}

// PaymentprocessorVoidPaymentResponse struct for PaymentprocessorVoidPaymentResponse
type PaymentprocessorVoidPaymentResponse struct {
	Transaction *PaymentprocessorTransaction `json:"transaction,omitempty"`
	ErrorMessage *string `json:"errorMessage,omitempty"`
}

// NewPaymentprocessorVoidPaymentResponse instantiates a new PaymentprocessorVoidPaymentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentprocessorVoidPaymentResponse() *PaymentprocessorVoidPaymentResponse {
	this := PaymentprocessorVoidPaymentResponse{}
	return &this
}

// NewPaymentprocessorVoidPaymentResponseWithDefaults instantiates a new PaymentprocessorVoidPaymentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentprocessorVoidPaymentResponseWithDefaults() *PaymentprocessorVoidPaymentResponse {
	this := PaymentprocessorVoidPaymentResponse{}
	return &this
}

// GetTransaction returns the Transaction field value if set, zero value otherwise.
func (o *PaymentprocessorVoidPaymentResponse) GetTransaction() PaymentprocessorTransaction {
	if o == nil || IsNil(o.Transaction) {
		var ret PaymentprocessorTransaction
		return ret
	}
	return *o.Transaction
}

// GetTransactionOk returns a tuple with the Transaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentprocessorVoidPaymentResponse) GetTransactionOk() (*PaymentprocessorTransaction, bool) {
	if o == nil || IsNil(o.Transaction) {
		return nil, false
	}
	return o.Transaction, true
}

// HasTransaction returns a boolean if a field has been set.
func (o *PaymentprocessorVoidPaymentResponse) HasTransaction() bool {
	if o != nil && !IsNil(o.Transaction) {
		return true
	}

	return false
}

// SetTransaction gets a reference to the given PaymentprocessorTransaction and assigns it to the Transaction field.
func (o *PaymentprocessorVoidPaymentResponse) SetTransaction(v PaymentprocessorTransaction) {
	o.Transaction = &v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise.
func (o *PaymentprocessorVoidPaymentResponse) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage) {
		var ret string
		return ret
	}
	return *o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentprocessorVoidPaymentResponse) GetErrorMessageOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorMessage) {
		return nil, false
	}
	return o.ErrorMessage, true
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *PaymentprocessorVoidPaymentResponse) HasErrorMessage() bool {
	if o != nil && !IsNil(o.ErrorMessage) {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given string and assigns it to the ErrorMessage field.
func (o *PaymentprocessorVoidPaymentResponse) SetErrorMessage(v string) {
	o.ErrorMessage = &v
}

func (o PaymentprocessorVoidPaymentResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentprocessorVoidPaymentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Transaction) {
		toSerialize["transaction"] = o.Transaction
	}
	if !IsNil(o.ErrorMessage) {
		toSerialize["errorMessage"] = o.ErrorMessage
	}
	return toSerialize, nil
}

type NullablePaymentprocessorVoidPaymentResponse struct {
	value *PaymentprocessorVoidPaymentResponse
	isSet bool
}

func (v NullablePaymentprocessorVoidPaymentResponse) Get() *PaymentprocessorVoidPaymentResponse {
	return v.value
}

func (v *NullablePaymentprocessorVoidPaymentResponse) Set(val *PaymentprocessorVoidPaymentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentprocessorVoidPaymentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentprocessorVoidPaymentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentprocessorVoidPaymentResponse(val *PaymentprocessorVoidPaymentResponse) *NullablePaymentprocessorVoidPaymentResponse {
	return &NullablePaymentprocessorVoidPaymentResponse{value: val, isSet: true}
}

func (v NullablePaymentprocessorVoidPaymentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentprocessorVoidPaymentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


