/*
Payment Processor Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paymentprocessor

import (
	"encoding/json"
)

// checks if the PaymentprocessorListPaymentMethodsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentprocessorListPaymentMethodsResponse{}

// PaymentprocessorListPaymentMethodsResponse struct for PaymentprocessorListPaymentMethodsResponse
type PaymentprocessorListPaymentMethodsResponse struct {
	Methods []PaymentprocessorPaymentMethod `json:"methods,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PaymentprocessorListPaymentMethodsResponse PaymentprocessorListPaymentMethodsResponse

// NewPaymentprocessorListPaymentMethodsResponse instantiates a new PaymentprocessorListPaymentMethodsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentprocessorListPaymentMethodsResponse() *PaymentprocessorListPaymentMethodsResponse {
	this := PaymentprocessorListPaymentMethodsResponse{}
	return &this
}

// NewPaymentprocessorListPaymentMethodsResponseWithDefaults instantiates a new PaymentprocessorListPaymentMethodsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentprocessorListPaymentMethodsResponseWithDefaults() *PaymentprocessorListPaymentMethodsResponse {
	this := PaymentprocessorListPaymentMethodsResponse{}
	return &this
}

// GetMethods returns the Methods field value if set, zero value otherwise.
func (o *PaymentprocessorListPaymentMethodsResponse) GetMethods() []PaymentprocessorPaymentMethod {
	if o == nil || IsNil(o.Methods) {
		var ret []PaymentprocessorPaymentMethod
		return ret
	}
	return o.Methods
}

// GetMethodsOk returns a tuple with the Methods field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentprocessorListPaymentMethodsResponse) GetMethodsOk() ([]PaymentprocessorPaymentMethod, bool) {
	if o == nil || IsNil(o.Methods) {
		return nil, false
	}
	return o.Methods, true
}

// HasMethods returns a boolean if a field has been set.
func (o *PaymentprocessorListPaymentMethodsResponse) HasMethods() bool {
	if o != nil && !IsNil(o.Methods) {
		return true
	}

	return false
}

// SetMethods gets a reference to the given []PaymentprocessorPaymentMethod and assigns it to the Methods field.
func (o *PaymentprocessorListPaymentMethodsResponse) SetMethods(v []PaymentprocessorPaymentMethod) {
	o.Methods = v
}

func (o PaymentprocessorListPaymentMethodsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentprocessorListPaymentMethodsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Methods) {
		toSerialize["methods"] = o.Methods
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaymentprocessorListPaymentMethodsResponse) UnmarshalJSON(data []byte) (err error) {
	varPaymentprocessorListPaymentMethodsResponse := _PaymentprocessorListPaymentMethodsResponse{}

	err = json.Unmarshal(data, &varPaymentprocessorListPaymentMethodsResponse)

	if err != nil {
		return err
	}

	*o = PaymentprocessorListPaymentMethodsResponse(varPaymentprocessorListPaymentMethodsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "methods")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *PaymentprocessorListPaymentMethodsResponse) GetValue() interface{} {
	if o == nil || IsNil(o.Type) || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}
// SetValue populate the value of well-known types
func (o *PaymentprocessorListPaymentMethodsResponse) SetValue(value interface{}) {
	if o == nil || IsNil(o.Type) || IsNil(value) {
		return
	}
    if IsNil(o.AdditionalProperties) {
        o.AdditionalProperties = map[string]interface{}{}
    }
	o.AdditionalProperties["value"] = value
	return
}
type NullablePaymentprocessorListPaymentMethodsResponse struct {
	value *PaymentprocessorListPaymentMethodsResponse
	isSet bool
}

func (v NullablePaymentprocessorListPaymentMethodsResponse) Get() *PaymentprocessorListPaymentMethodsResponse {
	return v.value
}

func (v *NullablePaymentprocessorListPaymentMethodsResponse) Set(val *PaymentprocessorListPaymentMethodsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentprocessorListPaymentMethodsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentprocessorListPaymentMethodsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentprocessorListPaymentMethodsResponse(val *PaymentprocessorListPaymentMethodsResponse) *NullablePaymentprocessorListPaymentMethodsResponse {
	return &NullablePaymentprocessorListPaymentMethodsResponse{value: val, isSet: true}
}

func (v NullablePaymentprocessorListPaymentMethodsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentprocessorListPaymentMethodsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


