/*
Payment Processor Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paymentprocessor

import (
	"encoding/json"
	"fmt"
)

// checks if the PaymentprocessorListPaymentMethodsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentprocessorListPaymentMethodsRequest{}

// PaymentprocessorListPaymentMethodsRequest struct for PaymentprocessorListPaymentMethodsRequest
type PaymentprocessorListPaymentMethodsRequest struct {
	TenantId string `json:"tenantId"`
	AuthenticateMethods *bool `json:"authenticateMethods,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PaymentprocessorListPaymentMethodsRequest PaymentprocessorListPaymentMethodsRequest

// NewPaymentprocessorListPaymentMethodsRequest instantiates a new PaymentprocessorListPaymentMethodsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentprocessorListPaymentMethodsRequest(tenantId string) *PaymentprocessorListPaymentMethodsRequest {
	this := PaymentprocessorListPaymentMethodsRequest{}
	this.TenantId = tenantId
	return &this
}

// NewPaymentprocessorListPaymentMethodsRequestWithDefaults instantiates a new PaymentprocessorListPaymentMethodsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentprocessorListPaymentMethodsRequestWithDefaults() *PaymentprocessorListPaymentMethodsRequest {
	this := PaymentprocessorListPaymentMethodsRequest{}
	return &this
}

// GetTenantId returns the TenantId field value
func (o *PaymentprocessorListPaymentMethodsRequest) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *PaymentprocessorListPaymentMethodsRequest) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *PaymentprocessorListPaymentMethodsRequest) SetTenantId(v string) {
	o.TenantId = v
}

// GetAuthenticateMethods returns the AuthenticateMethods field value if set, zero value otherwise.
func (o *PaymentprocessorListPaymentMethodsRequest) GetAuthenticateMethods() bool {
	if o == nil || IsNil(o.AuthenticateMethods) {
		var ret bool
		return ret
	}
	return *o.AuthenticateMethods
}

// GetAuthenticateMethodsOk returns a tuple with the AuthenticateMethods field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentprocessorListPaymentMethodsRequest) GetAuthenticateMethodsOk() (*bool, bool) {
	if o == nil || IsNil(o.AuthenticateMethods) {
		return nil, false
	}
	return o.AuthenticateMethods, true
}

// &#39;Has&#39;AuthenticateMethods returns a boolean if a field has been set.
func (o *PaymentprocessorListPaymentMethodsRequest) &#39;Has&#39;AuthenticateMethods() bool {
	if o != nil && !IsNil(o.AuthenticateMethods) {
		return true
	}

	return false
}

// SetAuthenticateMethods gets a reference to the given bool and assigns it to the AuthenticateMethods field.
func (o *PaymentprocessorListPaymentMethodsRequest) SetAuthenticateMethods(v bool) {
	o.AuthenticateMethods = &v
}

func (o PaymentprocessorListPaymentMethodsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentprocessorListPaymentMethodsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tenantId"] = o.TenantId
	if !IsNil(o.AuthenticateMethods) {
		toSerialize["authenticateMethods"] = o.AuthenticateMethods
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaymentprocessorListPaymentMethodsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tenantId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaymentprocessorListPaymentMethodsRequest := _PaymentprocessorListPaymentMethodsRequest{}

	err = json.Unmarshal(data, &varPaymentprocessorListPaymentMethodsRequest)

	if err != nil {
		return err
	}

	*o = PaymentprocessorListPaymentMethodsRequest(varPaymentprocessorListPaymentMethodsRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tenantId")
		delete(additionalProperties, "authenticateMethods")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *PaymentprocessorListPaymentMethodsRequest) GetValue() interface{} {
	if o == nil || IsNil(o.Type) || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}
// SetValue populate the value of well-known types
func (o *PaymentprocessorListPaymentMethodsRequest) SetValue(value interface{}) {
	if o == nil || IsNil(o.Type) || IsNil(value) {
		return
	}
    if IsNil(o.AdditionalProperties) {
        o.AdditionalProperties = map[string]interface{}{}
    }
	o.AdditionalProperties["value"] = value
	return
}
type NullablePaymentprocessorListPaymentMethodsRequest struct {
	value *PaymentprocessorListPaymentMethodsRequest
	isSet bool
}

func (v NullablePaymentprocessorListPaymentMethodsRequest) Get() *PaymentprocessorListPaymentMethodsRequest {
	return v.value
}

func (v *NullablePaymentprocessorListPaymentMethodsRequest) Set(val *PaymentprocessorListPaymentMethodsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentprocessorListPaymentMethodsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentprocessorListPaymentMethodsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentprocessorListPaymentMethodsRequest(val *PaymentprocessorListPaymentMethodsRequest) *NullablePaymentprocessorListPaymentMethodsRequest {
	return &NullablePaymentprocessorListPaymentMethodsRequest{value: val, isSet: true}
}

func (v NullablePaymentprocessorListPaymentMethodsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentprocessorListPaymentMethodsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


